<?php


namespace App\utils\Pmc\FormParts;


use App\Mail\PmcConfirmMail;
use App\utils\Pmc\AssetsProcessor;
use App\utils\Pmc\FormPartAbstract;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class FormPartPayment extends FormPartAbstract
{
    public function FillFromRequest(Request $request)
    {
        parent::FillFromRequest($request); // TODO: Change the autogenerated stub
    }

    public function toJson()
    {
        $json = parent::toJson();

        if('cib' === $this->model->path) {
            $json->productName = 'Campaign-in-a-Box Partner: Agency Fee';
            $json->productPrice = 750;
        } else {
            $json->productName = 'Custom Creative Partner: Agency Fee';
            $json->productPrice = 500;
        }

        return $json;
    }

    public function PaymentProcessed(Request $request) {
        $this->model->purchase_reference = $request->paymentReference;


//        teFBELMofUmS7mAWZvUwGF57gw1L6kzP

//        $this->model->prepared_asset_url = (new AssetsProcessor())->ProcessForm($this->model);
//        $this->model->confirmation_email_sent_at

//        try {
//            Mail::to([['email' => $this->model->email, 'name' => "{$this->model->first_name} {$this->model->last_name}", ], ])
//                ->send(new PmcConfirmMail($this->model));
//            $this->model->confirmation_email_sent_at = date('Y-m-d H:i:s');
//        } catch (\Exception $e) {
            //Ignore
//        }


        $this->model->save();
        return $this->model->prepared_asset_url;
    }
}
